server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    defer-datasource-initialization: true
  security:
    user:
      name: test
      password: test
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 6650094555-tp6l1j42l9eedqf7781u68tuo9om6chj.apps.googleusercontent.com
#            client-secret: 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
#            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
#            scope:
#              - email
#              - profile
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: swpprojectgr2@gmail.com
#    password: ssnj lzol jolo lljw
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
app:
  base-url: "http://localhost:8080"
